CREATE TABLE PUNTO_WEB_BITACORA(
	ID_BITACORA	int(11) AUTO_INCREMENT PRIMARY KEY,
	FECHA	date,
	REQUEST_ENDPOINT	varchar(500),
	RESPONSE_ENDPOINT	varchar(255),
	REQUEST_PUNTO_WEB	varchar(255),
	RESPONSE_PUNTO_WEB	text,
	DESCRIPCION	varchar(255),
	ID_APP	int(11),
	ID_PAIS	varchar(10),
	IDIOMA	varchar(20)
);